clean up (#6)

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -19,6 +19,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Create new tag
         id: create_tag
@@ -27,8 +29,15 @@ jobs:
           git config user.email github-actions@github.com
           LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
           NEW_TAG=$(echo $LAST_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
+          
+          # Check if the tag already exists
+          if git rev-parse $NEW_TAG >/dev/null 2>&1; then
+            echo "Tag $NEW_TAG already exists. Incrementing..."
+            NEW_TAG=$(echo $NEW_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
+          fi
+          
           git tag $NEW_TAG
-          git push origin $NEW_TAG
+          git push origin $NEW_TAG || echo "Failed to push tag $NEW_TAG. It might already exist remotely."
           echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
 
       - name: Set up Docker Buildx
